
# Configuration file for the folding assembly controller
folding_controller:
  saturation:
    v: 0.1
    w: 0.1
    gains:
      kf: 0.001
  breaking_error: 0.01 # When the part gets within **breaking_error** radians from the desired final orientation, the controller will start slowing down
  known_pc_distance: 0.20 #0.16 # used for testing the controller with no estimation
  base_frame: /base_link # name of the world frame (TF)
  ft_frame: /IRE0A004 # name of the force torque sensor frame (TF)
  # ft_sensor_offset: [0.0, 0.0, 0.0]
  ft_sensor_offset: [0.01, -0.043, -0.019]

folding_node:
  frequency: 100
  yumi_state_topic: /egmri_feedback_topic
  yumi_command_topic: /egmri_commanded_topic
  arm: left
  left_tooltip_name: left_gripper_base
  right_tooltip_name: right_gripper_base
  success_error: 0.01 # When the part gets within **success_error** radians from the desired final orientation, the node will succeed
  retreat_distance: 0.05 # meters to retreat the eef after succeeding in one assembly
  retreat_gain: 0.1 # proportional gain for the "position controller"
  retreat_error_threshold: 0.005
  gripper_command_topic: /abb_external_communication_node/rws_topic
  gripper_sleep_time: 3

# GOOD MESSAGE
#
# desired_velocities:
#   linear:
#     x: 0.0
#     y: 0.0
#     z: 0.0
#   angular:
#     x: 0.0
#     y: 0.0
#     z: -0.03
# final_orientation: -2.49120001558
# contact_force: 8.0
# estimate_type: 3
# force_control_type: 4
