ects_controller:
  alpha: 0.5
  beta: 1
  damping: 0.01
adaptive_estimator:
  alpha_force: 0.1
  beta_force: 0.01
  alpha_adapt_t: 1
  alpha_torque: 0.1
  beta_torque: 0.01
  alpha_adapt_r: 1
  torque_slack: 0
  max_force: 2
  max_torque: 0.1
kf_estimator:
  Q:
    data: [0.01, 0, 0,
           0, 0.01, 0,
           0, 0, 0.01]
  R:
    data: [0.01, 0, 0,
           0.0, 0.01, 0,
           0, 0, 0.01]
  ft_sensor_topic: /optoforce_node/wrench_IRE0A004



# GOOD MESSAGE
#
# desired_velocities:
#   linear:
#     x: 0.0
#     y: 0.0
#     z: 0.0
#   angular:
#     x: 0.0
#     y: 0.0
#     z: -0.03
# final_orientation: -2.49120001558
# contact_force: 8.0
# estimate_type: 3
# force_control_type: 4
