# Configuration file for the folding assembly controller
folding_controller:
  estimate: false
  saturation:
    v: 0.01
    w: 0.01
  gains:
    kf: 0.01
  known_pc_distance: 0.0 # used for testing the controller with no estimation

folding_node:
  frequency: 100
