# Configuration file for the contact point estimator
# Should define estimation related parameters

estimatorName: KF
config:
  noiseMatrices:
    process:
      rows: 3
      columns: 3
      # data: [0.00005, 0, 0, 0, 0.00005, 0, 0, 0, 0.00005]
      data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
    measurement:
      rows: 3
      columns: 3
      data: [0.01, 0, 0, 0.0, 0.01, 0, 0, 0, 0.01]
  initialCov:
    rows: 3
    columns: 3
    data: [1.0, 0, 0, 0.0, 1.0, 0, 0, 0, 1.0]
  ft_sensor_topic: /optoforce_node/wrench_IRE005
  z_offset: 0
