# Configuration file for the contact point estimator
# Should define estimation related parameters

estimatorName: KF
config:
  noiseMatrices:
    process:
      rows: 3
      columns: 3
      data: [0.00005, 0, 0, 0, 0.00005, 0, 0, 0, 0.00005]
    measurement:
      rows: 3
      columns: 3
      data: [0.25, 0, 0, 0.0, 0.25, 0, 0, 0, 0.25]
  initialCov:
    rows: 3
    columns: 3
    data: [0.01, 0, 0, 0.0, 0.01, 0, 0, 0, 0.01]
