# Configuration file for the folding assembly controller
# Should include desired set points and gains

saturationValues:
  linearVelocity: 0.1
  angularVelocity: 0.2
noEstimate:
  kp: 0.0005
  ki: 0.000025
