# Configuration file for the folding assembly controller
folding_controller:
  saturation:
    v: 0.1
    w: 0.1
  gains:
    kf: 0.005
  known_pc_distance: 0.14 #0.16 # used for testing the controller with no estimation
  base_frame: /base_link # name of the world frame (TF)
  ft_frame: /IRE0A004 # name of the force torque sensor frame (TF)

folding_node:
  frequency: 100
  yumi_state_topic: /egmri_feedback_topic
  yumi_command_topic: /egmri_commanded_topic
  arm: left
  left_tooltip_name: left_hand_base #left_gripper_base
  right_tooltip_name: right_hand_base #right_gripper_base
