# Configuration file for the contact point estimator
# Should define estimation related parameters

estimatorName: KF
config:
  noiseMatrices:
    process:
      rows: 3
      columns: 3
      data: [0.01, 0, 0, 0, 0.01, 0, 0, 0, 0.01]
    measurement:
      rows: 3
      columns: 3
      data: [0.01, 0, 0, 0.0, 0.01, 0, 0, 0, 0.01]
  initialCov:
    rows: 3
    columns: 3
    data: [1.0, 0, 0, 0.0, 1.0, 0, 0, 0, 1.0]
  ft_sensor_topic: /optoforce_node/wrench_IRE0A004
  z_offset: 0

folding_node:
  frequency: 100
