kinematic_chain_base_link: yumi_base_link
contact_point_offset: 0.15

rod_arm:
  kdl_eef_frame: "yumi_link_7_l"
  gripping_frame: "yumi_link_7_l" #"gripper_l_finger_l"
  has_ft_sensor: false
  sensor_frame: ""
  sensor_topic: ""

surface_arm:
  kdl_eef_frame: "yumi_link_7_r"
  gripping_frame: "yumi_link_7_r"
  has_ft_sensor: true
  sensor_frame: "yumi_link_7_r"
  sensor_topic: ""

kf_estimator:
  Q:
    data: [1000.01, 0, 0, 0, 1000.01, 0, 0, 0, 1000.01]
  R:
    data: [0.01, 0, 0, 0, 0.01, 0, 0, 0, 0.01]

pose_controller:
  vd_max: 0.01
  wd_max: 0.05
  position_gain: 1.0
  orientation_gain: 1.0

ects_controller:
  alpha: 1.0
  beta: 1
  inverse_damping: 0.0001

adaptive_estimator:
  alpha_force: 0.1
  beta_force: 0.01
  alpha_adapt_t: 1
  alpha_torque: 0.1
  beta_torque: 0.01
  alpha_adapt_r: 1
  torque_slack: 0.05
  max_force: 5
  max_torque: 0.2
