kinematic_chain_base_link: yumi_base_link
contact_point_offset: 0.085
# contact_point_offset: 0.21
action_name: folding_controller
use_computed_torque: false
use_ground_truth_pc: true
use_two_sensors: true
loop_rate: 250

kdl_manager:
  eps: 0.005
  max_tf_attempts: 10
  ikvel_solver: nso
  nso_weight: 40

rod_arm:
  kdl_eef_frame: "yumi_link_7_l"
  gripping_frame: "l_gripping_point" #"l_gripping_point" #"gripper_l_finger_l"
  has_ft_sensor: true
  sensor_frame: "optodaq_l_sensor_link"
  sensor_topic: "/yumi/optodaq_l/ft_compensated"
  sensor_calib:
    data: [1.0, 0, 0, 0, 0, 0,
           0, 1.0, 0, 0, 0, 0,
           0, 0, 1.0, 0, 0, 0,
           0, 0, 0, 1.0, 0, 0,
           0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 1]
    # data: [1.0, 0, 0, 0, 0, 0,
    #        0, 1.0, 0, 0, 0, 0,
    #        0, 0, 1.0, 0, 0, 0,
    #        0.03321, 0.03192, 0.01945, 1.635, 0.3909, 0.4423,
    #        0.07226, -0.02405, -0.008477, 0.02264, 2.037, 1.466,
    #        -0.001555, 0.01690, 0.002053, 0.1, -0.1903, 1.324]

surface_arm:
  kdl_eef_frame: "yumi_link_7_r"
  gripping_frame: "r_gripping_point"
  has_ft_sensor: true
  sensor_frame: "optodaq_r_sensor_link"
  sensor_topic: "/yumi/optodaq_r/ft_compensated"
  sensor_calib:
    data: [1.0, 0, 0, 0, 0, 0,
           0, 1.0, 0, 0, 0, 0,
           0, 0, 1.0, 0, 0, 0,
           0, 0, 0, 1.0, 0, 0,
           0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 1]
    # data: [1.0, 0, 0, 0, 0, 0,
    #        0, 1.0, 0, 0, 0, 0,
    #        0, 0, 1.0, 0, 0, 0,
    #        -0.04439, 0.00957, 0.02209, 1.909, -0.2187, 1.185,
    #        0.03042, -0.0124, -0.02158, -0.03745, 1.703, -0.1913,
    #        0.01091, 0.01725, -0.003834, -0.4139, 0.06982, 1.629]

kf_estimator:
  Q:
    data: [1, 0, 0, 0, 0, 0,
           0, 1, 0, 0, 0, 0,
           0, 0, 1, 0, 0, 0,
           0, 0, 0, 1.1, 0, 0,
           0, 0, 0, 0, 1.1, 0,
           0, 0, 0, 0, 0, 1.1]
    # data: [1, 0, 0,
    #        0, 1, 0,
    #        0, 0, 1]
  R:
    data: [0.01, 0, 0, 0, 0.01, 0, 0, 0, 0.01]

pose_controller:
  vd_max: 0.05
  wd_max: 0.25
  position_gain: 0.1
  orientation_gain: 0.1

ects_controller:
  alpha: 0.5
  beta: 1
  inverse_damping: 0.0001

grasp:
  translational_axis: z
  rotational_axis: -x #y

adaptive_estimator:
  alpha_force: -0.00 # 0.01
  beta_force: -0.0
  force_slack: 0.0
  alpha_adapt_t: 0
  alpha_torque: 0.0
  beta_torque: -0.00
  alpha_adapt_r: 0
  torque_slack: 0.0
  max_force: 5
  max_torque: 0.2
