kinematic_chain_base_link: yumi_base_link
contact_point_offset: 0.0875
action_name: folding_controller

kdl_manager:
  eps: 0.001
  max_tf_attempts: 10

rod_arm:
  kdl_eef_frame: "yumi_link_7_l"
  gripping_frame: "l_gripping_point" #"gripper_l_finger_l"
  has_ft_sensor: true
  sensor_frame: "optodaq_l_sensor_link"
  sensor_topic: "/yumi/optodaq_l_compensated"

surface_arm:
  kdl_eef_frame: "yumi_link_7_r"
  gripping_frame: "r_gripping_point"
  has_ft_sensor: true
  sensor_frame: "optodaq_r_sensor_link"
  sensor_topic: "/yumi/optodaq_r_compensated"

kf_estimator:
  Q:
    data: [50.01, 0, 0, 0, 0, 0,
           0, 50.01, 0, 0, 0, 0,
           0, 0, 50.01, 0, 0, 0,
           0, 0, 0, 10.01, 0, 0,
           0, 0, 0, 0, 10.01, 0,
           0, 0, 0, 0, 0, 10.01]
  R:
    data: [0.01, 0, 0, 0, 0.01, 0, 0, 0, 0.01]

pose_controller:
  vd_max: 0.05
  wd_max: 0.25
  position_gain: 0.1
  orientation_gain: 0.1

ects_controller:
  alpha: 0.5
  beta: 1
  inverse_damping: 0.0001

grasp:
  translational_axis: z
  rotational_axis: -x

adaptive_estimator:
  alpha_force: -0.01 # 0.01
  beta_force: -0.0
  force_slack: 0.5
  alpha_adapt_t: 0
  alpha_torque: 0.3
  beta_torque: -0.0
  alpha_adapt_r: 0
  torque_slack: 0.05
  max_force: 5
  max_torque: 0.2
